// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-K8w9H1mJPe1tu72cFGFXnF3J1RReniM',
    appId: '1:630518753461:web:b04ba6b94a1fc3001736fc',
    messagingSenderId: '630518753461',
    projectId: 'serenescene-29148',
    authDomain: 'serenescene-29148.firebaseapp.com',
    storageBucket: 'serenescene-29148.firebasestorage.app',
    measurementId: 'G-CMSQ1LX127',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7sKqB_yLSVi6ucgwNqlmS-T6w49eRu1w',
    appId: '1:630518753461:android:52babd71a27251491736fc',
    messagingSenderId: '630518753461',
    projectId: 'serenescene-29148',
    storageBucket: 'serenescene-29148.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAFitjxcWQJK-YxiOc2x3PXtSWPpUmXpI',
    appId: '1:630518753461:ios:f02b75093009cc9c1736fc',
    messagingSenderId: '630518753461',
    projectId: 'serenescene-29148',
    storageBucket: 'serenescene-29148.firebasestorage.app',
    iosClientId: '630518753461-f0n6t4f9h1b1t7t0d41cirto5765bn12.apps.googleusercontent.com',
    iosBundleId: 'com.example.providerTamplete',
  );
}
